# SPDX-License-Identifier: AGPL-3.0-or-later
# Dependabot configuration for 688 Attack Hub.
# There are no package ecosystems to monitor — the game has no dependencies,
# and package.json declares none. Only github-actions is watched, to keep
# workflow action versions current.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
